spring:
  application:
    name: GBW-Web-App-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1255
    url: jdbc:postgresql://localhost:5432/gbw_app_backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8081



file:
  saving:
    directory:
      base:
        dir: 'D:'
        sub:
          dir: GBWAYFILES
          resumes: Resumes
          news: News



jwt:
  secret: zK9V3QxrH8L2Wn9cNxLmTd9ZxHzo8JWlMkLg9rGgjNU=

admin:
  username: gbwadmin
  password: $2a$10$Cm6iOnqsTjb1LFMHfnL55uGNKxm0dvgqdHB/Lr.6NqKdroXN3jeP6

