spring:
  application:
    name: GBW-Web-App-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: { username }
    password: { password }
    url: jdbc:postgresql://83.69.135.51:5432/apigbwayuz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 7MB

server:
  port: 7878



file:
  saving:
    directory:
      base:
        dir: 'D:'
        sub:
          dir: GBWAYFILES
          resumes: Resumes
          news: News




