spring:
  application:
    name: GBW-Web-App-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: gbway
    password: Gb12345db
    url: jdbc:postgresql://83.69.135.51:5432/apigbwayuz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 7MB

server:
  port: 7878



file:
  saving:
    directory:
      base:
        dir: 'D:'
        sub:
          dir: GBWAYFILES
          resumes: Resumes
          news: News


jwt:
  secret: zK9V3QxrH8L2Wn9cNxLmTd9ZxHzo8JWlMkLg9rGgjNU=

admin:
  username: gbway
  password: $2y$10$t6xgi58NwfiiEo2ZDBuVZekkic1p1YxxT758kg4js3V82.V9G7WfG


