spring:
  application:
    name: GBW-Web-App-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2365
    url: jdbc:postgresql://localhost:5432/gbw_app_backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8081



file:
  saving:
    directory:
      base:
        dir: 'D:'
        sub:
          dir: GBWAYFILES
          resumes: Resumes
          news: News




